const GET_MONTH_REQUEST = 'getMonth/REQUEST';
const GET_MONTH_SUCCESS = 'getMonth/SUCCESS';
const GET_MONTH_ERROR = 'getMonth/ERROR';

export {
  GET_MONTH_REQUEST,
  GET_MONTH_SUCCESS,
  GET_MONTH_ERROR,
};
